In [2]:
import pandas as pd
df = pd.read_csv('netflix_data.csv')
df.head()

,Show_Id,Category,Title,Director,Cast,Country,Release_Date,Rating,Duration,Type,Description
0,s1,TV Show,3%,NaN,"João Miguel, Bianca Comparato, Michel Gomes, R...",Brazil,"August 14, 2020",TV-MA,4 Seasons,"International TV Shows, TV Dramas, TV Sci-Fi &...",In a future where the elite inhabit an island ...
1,s2,Movie,07:19,Jorge Michel Grau,"Demián Bichir, Héctor Bonilla, Oscar Serrano, ...",Mexico,"December 23, 2016",TV-MA,93 min,"Dramas, International Movies",After a devastating earthquake hits Mexico Cit...
2,s3,Movie,23:59,Gilbert Chan,"Tedd Chan, Stella Chung, Henley Hii, Lawrence ...",Singapore,"December 20, 2018",R,78 min,"Horror Movies, International Movies","When an army recruit is found dead, his fellow..."
3,s4,Movie,9,Shane Acker,"Elijah Wood, John C. Reilly, Jennifer Connelly...",United States,"November 16, 2017",PG-13,80 min,"Action & Adventure, Independent Movies, Sci-Fi...","In a postapocalyptic world, rag-doll robots hi..."
4,s5,Movie,21,Robert Luketic,"Jim Sturgess, Kevin Spacey, Kate Bosworth, Aar...",United States,"January 1, 2020",PG-13,123 min,Dramas,A brilliant group of students become card-coun...

In [9]:
import pandas as pd
df = pd.read_csv('netflix_data.csv')

print(df[df.duplicated()])
df.drop_duplicates(inplace=True)
print(df[df.duplicated()])

     Show_Id Category              Title        Director  \
6300    s684    Movie           Backfire     Dave Patten
6622   s6621    Movie  The Lost Okoroshi  Abba T. Makama

                                                   Cast        Country  \
6300  Black Deniro, Byron "Squally" Vinson, Dominic ...  United States
6622  Seun Ajayi, Judith Audu, Tope Tedela, Ifu Enna...        Nigeria

           Release_Date Rating Duration  \
6300      April 5, 2019  TV-MA   97 min
6622  September 4, 2020  TV-MA   94 min

                                       Type  \
6300  Dramas, Independent Movies, Thrillers
6622   Comedies, Dramas, Independent Movies

                                            Description
6300  When two would-be robbers accidentally kill a ...
6622  A disillusioned security guard transforms into...
Empty DataFrame
Columns: [Show_Id, Category, Title, Director, Cast, Country, Release_Date, Rating, Duration, Type, Description]
Index: []

In [4]:
import pandas as pd
df = pd.read_csv('netflix_data.csv')
df.isnull().sum()

Show_Id            0
Category           0
Title              0
Director        2388
Cast             718
Country          507
Release_Date      10
Rating             7
Duration           0
Type               0
Description        0
dtype: int64

In [29]:
import pandas as pd
df = pd.read_csv('netflix_data.csv')
p = df[df['Title']=="House of cards"]
print(p)
print(list(p['Show_Id']))
print(list(p['Director']))

Empty DataFrame
Columns: [Show_Id, Category, Title, Director, Cast, Country, Release_Date, Rating, Duration, Type, Description]
Index: []
[]
[]

In [37]:
import pandas as pd
df = pd.read_csv('netflix_data.csv')
p = df['Release_Date'].value_counts().max()
p

118

In [52]:
import pandas as pd
df = pd.read_csv('netflix_data.csv')
p = df['Show_Id'].unique()

len(list(p))

7787

In [18]:
import pandas as pd
df = pd.read_csv('netflix_data.csv')

df

,Show_Id,Category,Title,Director,Cast,Country,Release_Date,Rating,Duration,Type,Description
0,s1,TV Show,3%,NaN,"João Miguel, Bianca Comparato, Michel Gomes, R...",Brazil,"August 14, 2020",TV-MA,4 Seasons,"International TV Shows, TV Dramas, TV Sci-Fi &...",In a future where the elite inhabit an island ...
1,s2,Movie,07:19,Jorge Michel Grau,"Demián Bichir, Héctor Bonilla, Oscar Serrano, ...",Mexico,"December 23, 2016",TV-MA,93 min,"Dramas, International Movies",After a devastating earthquake hits Mexico Cit...
2,s3,Movie,23:59,Gilbert Chan,"Tedd Chan, Stella Chung, Henley Hii, Lawrence ...",Singapore,"December 20, 2018",R,78 min,"Horror Movies, International Movies","When an army recruit is found dead, his fellow..."
3,s4,Movie,9,Shane Acker,"Elijah Wood, John C. Reilly, Jennifer Connelly...",United States,"November 16, 2017",PG-13,80 min,"Action & Adventure, Independent Movies, Sci-Fi...","In a postapocalyptic world, rag-doll robots hi..."
4,s5,Movie,21,Robert Luketic,"Jim Sturgess, Kevin Spacey, Kate Bosworth, Aar...",United States,"January 1, 2020",PG-13,123 min,Dramas,A brilliant group of students become card-coun...
...,...,...,...,...,...,...,...,...,...,...,...
7784,s7783,Movie,Zozo,Josef Fares,"Imad Creidi, Antoinette Turk, Elias Gergi, Car...","Sweden, Czech Republic, United Kingdom, Denmar...","October 19, 2020",TV-MA,99 min,"Dramas, International Movies",When Lebanon's Civil War deprives Zozo of his ...
7785,s7784,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...
7786,s7785,Movie,Zulu Man in Japan,NaN,Nasty C,NaN,"September 25, 2020",TV-MA,44 min,"Documentaries, International Movies, Music & M...","In this documentary, South African rapper Nast..."
7787,s7786,TV Show,Zumbo's Just Desserts,NaN,"Adriano Zumbo, Rachel Khoo",Australia,"October 31, 2020",TV-PG,1 Season,"International TV Shows, Reality TV",Dessert wizard Adriano Zumbo looks for the nex...
7788,s7787,Movie,ZZ TOP: THAT LITTLE OL' BAND FROM TEXAS,Sam Dunn,NaN,"United Kingdom, Canada, United States","March 1, 2020",TV-MA,90 min,"Documentaries, Music & Musicals",This documentary delves into the mystique behi...

In [8]:

# df["Date_N"]=pd.to_datetime(df["Release_Date"])
import pandas as pd
df = pd.read_csv('netflix_data.csv')

# df = pd.DataFrame({'InsertedDate': pd.to_datetime(df["Release_Date"])})

# df['Year'] = df['InsertedDate'].dt.strftime('%Y')
# print(df)
# df['Year'] = df["Release_Date"].dt.strftime('%Y')


df['year'] = pd.DatetimeIndex(df['Release_Date']).year
df[(df['Category']=='Movie') &  (df['year']==2020.0)]

,Show_Id,Category,Title,Director,Cast,Country,Release_Date,Rating,Duration,Type,Description,year
4,s5,Movie,21,Robert Luketic,"Jim Sturgess, Kevin Spacey, Kate Bosworth, Aar...",United States,"January 1, 2020",PG-13,123 min,Dramas,A brilliant group of students become card-coun...,2020.0
6,s7,Movie,122,Yasir Al Yasiri,"Amina Khalil, Ahmed Dawood, Tarek Lotfy, Ahmed...",Egypt,"June 1, 2020",TV-MA,95 min,"Horror Movies, International Movies","After an awful accident, a couple admitted to ...",2020.0
14,s15,Movie,3022,John Suits,"Omar Epps, Kate Walsh, Miranda Cosgrove, Angus...",United States,"March 19, 2020",R,91 min,"Independent Movies, Sci-Fi & Fantasy, Thrillers",Stranded when the Earth is suddenly destroyed ...,2020.0
27,s28,Movie,#Alive,Cho Il,"Yoo Ah-in, Park Shin-hye",South Korea,"September 8, 2020",TV-MA,99 min,"Horror Movies, International Movies, Thrillers","As a grisly virus rampages a city, a lone man ...",2020.0
28,s29,Movie,#AnneFrank - Parallel Stories,"Sabina Fedeli, Anna Migotto","Helen Mirren, Gengher Gatti",Italy,"July 1, 2020",TV-14,95 min,"Documentaries, International Movies","Through her diary, Anne Frank's story is retol...",2020.0
...,...,...,...,...,...,...,...,...,...,...,...,...
7762,s7761,Movie,Zaki Chan,Wael Ihsan,"Ahmed Helmy, Yasmin Abdulaziz, Hassan Hosny, H...",Egypt,"May 19, 2020",TV-PG,109 min,"Comedies, International Movies, Romantic Movies",An unqualified young man has his work cut out ...,2020.0
7783,s7782,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero...",2020.0
7784,s7783,Movie,Zozo,Josef Fares,"Imad Creidi, Antoinette Turk, Elias Gergi, Car...","Sweden, Czech Republic, United Kingdom, Denmar...","October 19, 2020",TV-MA,99 min,"Dramas, International Movies",When Lebanon's Civil War deprives Zozo of his ...,2020.0
7786,s7785,Movie,Zulu Man in Japan,NaN,Nasty C,NaN,"September 25, 2020",TV-MA,44 min,"Documentaries, International Movies, Music & M...","In this documentary, South African rapper Nast...",2020.0
7788,s7787,Movie,ZZ TOP: THAT LITTLE OL' BAND FROM TEXAS,Sam Dunn,NaN,"United Kingdom, Canada, United States","March 1, 2020",TV-MA,90 min,"Documentaries, Music & Musicals",This documentary delves into the mystique behi...,2020.0

In [77]:
import pandas as pd
df = pd.read_csv('netflix_data.csv')
p=df[(df['Country']=='India') & (df['Category']=='TV Show')]
p['Title']

86            21 Sarfarosh: Saragarhi 1897
132                              7 (Seven)
340                           Agent Raghav
364                           Akbar Birbal
533                    Anjaan: Rural Myths
                       ...
6249                  The Creative Indians
6400    The Golden Years with Javed Akhtar
6469                The House That Made Me
7294                            Typewriter
7705                       Yeh Meri Family
Name: Title, Length: 71, dtype: object

In [79]:
import pandas as pd
df = pd.read_csv('netflix_data.csv')
p = df['Director'].value_counts()
p.head(10)

Director
Raúl Campos, Jan Suter    18
Marcus Raboy              16
Jay Karas                 14
Cathy Garcia-Molina       13
Jay Chapman               12
Youssef Chahine           12
Martin Scorsese           12
Steven Spielberg          10
David Dhawan               9
Robert Rodriguez           8
Name: count, dtype: int64

In [80]:
import pandas as pd
df = pd.read_csv('netflix_data.csv')
p=df[(df['Country']=='Unite Kingdom') |( (df['Category']=='Movie') & (df['Type']=='Comedies'))]
p['Title']

33                     #realityhigh
72                         17 Again
84                        21 & Over
148            A Bad Moms Christmas
174     A Futile and Stupid Gesture
                   ...
7341           Undercover Brother 2
7590              Where's the Money
7623                      Wild Oats
7634                   Wine Country
7664                        Work It
Name: Title, Length: 97, dtype: object

In [101]:
import pandas as pd
df = pd.read_csv('netflix_data.csv')
p = df[(df['Cast']=='Tom Cruise')]
p['Title'].count()

0

In [91]:
import pandas as pd
df = pd.read_csv('netflix_data.csv')
list(df['Rating'].unique())

['TV-MA',
 'R',
 'PG-13',
 'TV-14',
 'TV-PG',
 'NR',
 'TV-G',
 'TV-Y',
 nan,
 'TV-Y7',
 'PG',
 'G',
 'NC-17',
 'TV-Y7-FV',
 'UR']

In [103]:
import pandas as pd
df = pd.read_csv('netflix_data.csv')
p=df[(df['Country']=='Canada') & (df['Category']=='Movie') & (df['Rating']=='TV-14')]
p['Title'].count()

11

In [105]:
import pandas as pd
df = pd.read_csv('netflix_data.csv')
x = df['Release_Date']

    
p = df[(df['Release_Date'] > str(2020) ) &  (df['Category']=='TV Show') &  (df['Rating']=='R')]
p

,Show_Id,Category,Title,Director,Cast,Country,Release_Date,Rating,Duration,Type,Description
4497,s4498,TV Show,Nobel,NaN,"Aksel Hennie, Tuva Novotny, Anders Danielsen L...",Norway,"December 10, 2016",R,1 Season,"International TV Shows, TV Dramas, TV Thrillers",A series of incidents in Afghanistan set compl...
6437,s6436,TV Show,The Hateful Eight: Extended Version,Quentin Tarantino,"Samuel L. Jackson, Kurt Russell, Jennifer Jaso...",NaN,"April 25, 2019",R,1 Season,TV Shows,Trapped at a stagecoach stop as a storm rages ...

In [29]:
import pandas as pd
df = pd.read_csv('netflix_data.csv')
p=df[(df['Category']=='TV Show')]

country= p['Country'].value_counts().head()
country

Country
United States     705
United Kingdom    204
Japan             157
South Korea       147
India              71
Name: count, dtype: int64

In [134]:
import pandas as pd
df = pd.read_csv('netflix_data.csv')
p=df.sort_values('Release_Date')
p

,Show_Id,Category,Title,Director,Cast,Country,Release_Date,Rating,Duration,Type,Description
6673,s6672,TV Show,The Minimighty Kids,NaN,NaN,France,"April 15, 2018",TV-G,2 Seasons,"Kids' TV, TV Comedies","Some have big feet or a sniffly nose, others a..."
4261,s4262,TV Show,Mr. Young,NaN,"Brendan Meyer, Matreya Fedor, Gig Morton, Kurt...",Canada,"April 16, 2019",TV-G,2 Seasons,"Kids' TV, TV Comedies","After Adam graduates from college at age 14, h..."
3730,s3731,TV Show,Lost Girl,NaN,"Anna Silk, Kris Holden-Ried, Ksenia Solo, Rich...",Canada,"April 17, 2016",TV-14,5 Seasons,"TV Dramas, TV Horror, TV Mysteries",Discovering she's a succubus who sustains hers...
6247,s6247,TV Show,The Cravings,NaN,"Park Hee-bon, Phillip Choi, Hong Wan-pyo, Choi...",South Korea,"April 20, 2017",TV-14,2 Seasons,"International TV Shows, Korean TV Shows, TV Co...",Thirtysomething career woman Jae-yeong attempt...
1315,s1316,TV Show,Chewing Gum,NaN,"Michaela Coel, John Macmillan, Robert Lonsdale...",United Kingdom,"April 4, 2017",TV-MA,2 Seasons,"British TV Shows, International TV Shows, Roma...","The virginal Tracey, who was raised in a stric..."
...,...,...,...,...,...,...,...,...,...,...,...
3374,s3375,TV Show,Kikoriki,NaN,Igor Dmitriev,NaN,NaN,TV-Y,2 Seasons,Kids' TV,A wacky rabbit and his gang of animal pals hav...
3492,s3493,TV Show,La Familia P. Luche,NaN,"Eugenio Derbez, Consuelo Duval, Luis Manuel Áv...",United States,NaN,TV-14,3 Seasons,"International TV Shows, Spanish-Language TV Sh...","This irreverent sitcom featues Ludovico, Feder..."
3946,s3947,TV Show,Maron,NaN,"Marc Maron, Judd Hirsch, Josh Brener, Nora Zeh...",United States,NaN,TV-MA,4 Seasons,TV Comedies,"Marc Maron stars as Marc Maron, who interviews..."
5138,s5138,TV Show,Red vs. Blue,NaN,"Burnie Burns, Jason Saldaña, Gustavo Sorola, G...",United States,NaN,NR,13 Seasons,"TV Action & Adventure, TV Comedies, TV Sci-Fi ...","This parody of first-person shooter games, mil..."
6066,s6066,TV Show,The Adventures of Figaro Pho,NaN,"Luke Jurevicius, Craig Behenna, Charlotte Haml...",Australia,NaN,TV-Y7,2 Seasons,"Kids' TV, TV Comedies","Imagine your worst fears, then multiply them: ..."